
from('knative:channel/in')
  .convertBodyTo(String.class)
  .log('Received: ${body}')
  .choice()
    .when().simple('${body} startsWith \'exec: \'')
      .split().tokenize('\\s')
        .filter().simple('${body} != \'exec:\'')
          .log('Sending to channel out: ${body}')
          .to('knative:channel/out')
        .end()
      .end()
    .otherwise()
      .log('Discarding ${body} to dev-null channel')
      .to('knative:channel/dev-null')
